//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcControlsToolkit.Core {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DefaultMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal DefaultMessages() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MvcControlsToolkit.Core.DefaultMessages", typeof(DefaultMessages).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0} must be a date.
        /// </summary>
        public static string ClientFieldMustBeDate {
            get {
                return ResourceManager.GetString("ClientFieldMustBeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0} must be a date +time.
        /// </summary>
        public static string ClientFieldMustBeDateTime {
            get {
                return ResourceManager.GetString("ClientFieldMustBeDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0} must be an integer.
        /// </summary>
        public static string ClientFieldMustBeInteger {
            get {
                return ResourceManager.GetString("ClientFieldMustBeInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0} must be a date.
        /// </summary>
        public static string ClientFieldMustBeMonth {
            get {
                return ResourceManager.GetString("ClientFieldMustBeMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0} must be a number.
        /// </summary>
        public static string ClientFieldMustBeNumber {
            get {
                return ResourceManager.GetString("ClientFieldMustBeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0} must be a positive integer.
        /// </summary>
        public static string ClientFieldMustBePositiveInteger {
            get {
                return ResourceManager.GetString("ClientFieldMustBePositiveInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0} must be a time.
        /// </summary>
        public static string ClientFieldMustBeTime {
            get {
                return ResourceManager.GetString("ClientFieldMustBeTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0} must be a date.
        /// </summary>
        public static string ClientFieldMustBeWeek {
            get {
                return ResourceManager.GetString("ClientFieldMustBeWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0} is not a valid color.
        /// </summary>
        public static string ColorAttribute {
            get {
                return ResourceManager.GetString("ColorAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0} is not a valid e-mail.
        /// </summary>
        public static string EmailAddressAttribute {
            get {
                return ResourceManager.GetString("EmailAddressAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0} is not a valid web address.
        /// </summary>
        public static string UrlAttribute {
            get {
                return ResourceManager.GetString("UrlAttribute", resourceCulture);
            }
        }
    }
}
