// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using MvcControlsToolkit.Core.OData.Test.Data;
using System;

namespace MvcControlsToolkit.Core.OData.Test.Data.Migrations
{
    [DbContext(typeof(TestContext))]
    [Migration("20171108205512_update2")]
    partial class update2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MvcControlsToolkit.Core.OData.Test.Models.NestedReferenceModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AInt");

                    b.Property<string>("AString");

                    b.Property<int>("FatherId");

                    b.HasKey("Id");

                    b.HasIndex("FatherId");

                    b.ToTable("NestedReferenceModels");
                });

            modelBuilder.Entity("MvcControlsToolkit.Core.OData.Test.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Male");

                    b.Property<string>("Name");

                    b.Property<int?>("ParentId");

                    b.Property<int?>("SpouseOfId");

                    b.Property<string>("Surname");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("SpouseOfId")
                        .IsUnique()
                        .HasFilter("[SpouseOfId] IS NOT NULL");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("MvcControlsToolkit.Core.OData.Test.Models.ReferenceModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("ABool");

                    b.Property<DateTime>("ADate");

                    b.Property<DateTime>("ADateTime");

                    b.Property<DateTimeOffset>("ADateTimeOffset");

                    b.Property<decimal>("ADecimal");

                    b.Property<double>("ADouble");

                    b.Property<TimeSpan>("ADuration");

                    b.Property<float>("AFloat");

                    b.Property<Guid>("AGuid");

                    b.Property<int>("AInt");

                    b.Property<long>("ALong");

                    b.Property<DateTime>("AMonth");

                    b.Property<bool?>("ANBool");

                    b.Property<DateTime?>("ANDate");

                    b.Property<DateTime?>("ANDateTime");

                    b.Property<DateTimeOffset?>("ANDateTimeOffset");

                    b.Property<decimal?>("ANDecimal");

                    b.Property<double?>("ANDouble");

                    b.Property<TimeSpan?>("ANDuration");

                    b.Property<float?>("ANFloat");

                    b.Property<Guid?>("ANGuid");

                    b.Property<int?>("ANInt");

                    b.Property<long?>("ANLong");

                    b.Property<DateTime?>("ANMonth");

                    b.Property<short?>("ANShort");

                    b.Property<TimeSpan?>("ANTime");

                    b.Property<DateTime?>("ANWeek");

                    b.Property<short>("AShort");

                    b.Property<string>("AString");

                    b.Property<TimeSpan>("ATime");

                    b.Property<DateTime>("AWeek");

                    b.HasKey("Id");

                    b.ToTable("ReferenceModels");
                });

            modelBuilder.Entity("MvcControlsToolkit.Core.OData.Test.Models.NestedReferenceModel", b =>
                {
                    b.HasOne("MvcControlsToolkit.Core.OData.Test.Models.ReferenceModel", "Father")
                        .WithMany("Children")
                        .HasForeignKey("FatherId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MvcControlsToolkit.Core.OData.Test.Models.Person", b =>
                {
                    b.HasOne("MvcControlsToolkit.Core.OData.Test.Models.Person", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.HasOne("MvcControlsToolkit.Core.OData.Test.Models.Person", "Spouse")
                        .WithOne("SpouseOf")
                        .HasForeignKey("MvcControlsToolkit.Core.OData.Test.Models.Person", "SpouseOfId");
                });
#pragma warning restore 612, 618
        }
    }
}
